osx_image: xcode12
language: swift
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem install cocoapods --pre
install: echo "<3"
env:
  - MODE=framework
  - MODE=spm
  - MODE=examples
script: ./build.sh $MODE

# whitelist
branches:
  only:
    - master
